"""Agent-ready guardrails: the Work Map as plain instructions another agent can load, stopping where the expert would.
Only active rules are exported; each carries its status so a downstream agent never treats a hypothesis as expert-confirmed."""
from . import guard, slots as S

HEADER = """# Care-documentation guardrails (generated by Apprentice)
Scope: documentation and escalation coaching for refusal-of-care incidents. NOT diagnosis or treatment.
Always hand pain, medication, injury, acute deterioration and any uncertainty to a qualified human (nurse, coordinating physician, team meeting).
Status labels: CONFIRMED = an expert reviewed or taught it back; EXPERT-STATED = said live but not yet confirmed; HYPOTHESIS = learned from interview transcripts only.
"""


def status(r: dict, taught_back: str) -> str:
    if r.get("reviewed") == "confirmed" or taught_back in ("confirmed", "corrected"):
        return "CONFIRMED"
    live = any(it.get("live") for sl in S.SLOTS for it in ([r["slots"][sl]] if not isinstance(r["slots"][sl], list) else r["slots"][sl]))
    return "EXPERT-STATED" if live else "HYPOTHESIS"


def build(rules: list[dict], teachback: dict, map_version: str) -> str:
    lines = [HEADER, f"Work Map version: {map_version}\n"]
    for r in sorted((x for x in rules if not x.get("rejected")), key=lambda x: (-x["risk"], x["id"])):
        stop = r["predicate"]["severity"] == "block"
        action = r["slots"]["action"].get("live_text") or r["slots"]["action"]["text"]
        route = r["slots"]["escalation"].get("live_text") or r["slots"]["escalation"]["text"]
        lines += [f"## {r['id']}: {r['title']}  [{status(r, teachback.get(r['id'], 'none'))}{', learned from all interviews' if r.get('learned') else ''}]",
                  f"- {'STOP, do not save' if stop else 'WARN'} when: {guard.render(r['predicate'])}",
                  f"- Instead: {action}" if action else "- Instead: (not stated)"]
        lines += [f"- Guardrail: {g['text']}" for g in r["slots"]["guardrails"]]
        lines += [f"- Exception named by an expert: {e['text']}" for e in r["slots"]["exceptions"]]
        if route:
            lines.append(f"- Hand over to: {route}")
        lines.append(f"- Evidence: {', '.join(sorted({s['unit_id'] for s in r['sources']}))}\n")
    return "\n".join(lines)
